name: Node.js CI

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 5 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🍽️ Get working copy
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: 🍳 Pull Dependencies
        run: npm install
      - name: 🍳 Make Quote
        run: npm run deploy
      - name: 🚀 Deploy
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          echo "today=$(date +%y/%m/%d)" >> $GITHUB_ENV
          git add .
          git commit -m ":fire: updated README.md :memo:"|| echo updated on $today
          git push -f
